version: '3.8'

services:
  mongo:
    container_name: clean-java-mongo
    image: mongo:5.0
    restart: always
    volumes:
      - /opt/clean-java-api/mongo:/data/db
    ports:
      - "27017:27017"

  api:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
