micronaut:
  application:
    name: intro-micronaut

  server:
    port: 8080

logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    org: INFO